<?php

	include_once '../helpers/httpProvider.php';

	class Cliente{

		function incluirCliente($inputNome, $inputEmail, $inputTelefone, $inputCelular, $inputNascimento,
								$inputRg, $inputCpf, $inputEstadoCivil, $inputProfissao, $inputCep, $inputEndereco,
								$inputEnderecoNumero, $inputEnderecoComplemento, $inputEnderecoBairro, $inputEnderecoCidade,
								$inputEnderecoEstado, $inputEnderecoUf, $inputEnderecoComercial, $inputTelefoneComercial,
								$inputNumeroCnh, $inputValidadeCnh, $inputCategoriaCnh, $inputCidadeEstadoCnh, $inputServico,
									$inputConsultor, $inputMidia, $inputFormaPagamento, $inputFluxoAtendimento, $inputQuantidadeServico,
									$inputNumeroParcelas, $inputValorParcelas, $inputInstituicao, $inputValordePagamento, $inputValorEntrada,
									$inputNumeroParcelasServico, $inputMarcaVeiculo, $inputModeloVeiculo, $inputAnoVeiculo, $inputAnoModeloVeiculo,
									$inputPlacaVeiculo, $observacao, $inputDataAgendamento, $idUsuario, $idEmpresa){
			$httpProvider = new HttpProvider();
			$requestBody = ["id_usuario_inclusao" => $idUsuario,
							"id_usuario_alteracao" => $idUsuario,
							"nome_cliente" => $inputNome,
							"email" => $inputEmail,
							"telefone" => $inputTelefone,
							"celular" => $inputCelular,
							"rg" => $inputRg,
							"cpf" => $inputCpf,
							"endereco" => $inputEndereco,
							"numero" => $inputEnderecoNumero,
							"complemento" => $inputEnderecoComplemento,
							"bairro" => $inputEnderecoBairro,
							"cep" => $inputCep,
							"estado" => $inputEnderecoEstado,
							"cidade" => $inputEnderecoCidade,
							"uf" => $inputEnderecoUf,
							"endereco_comercial" => $inputEnderecoComercial,
							"telefone_comercial" => $inputTelefoneComercial,
							"estado_civil" => $inputEstadoCivil,
							"profissao" => $inputProfissao,
							"data_nasc" => $inputNascimento,
							"cnh" => $inputNumeroCnh,
							"validade_cnh" => $inputValidadeCnh,
							"categoria_cnh" => $inputCategoriaCnh,
							"cidade_estado_cnh" => $inputCidadeEstadoCnh,
							"id_fluxo_atendimento" => $inputFluxoAtendimento,
							"id_servico" => $inputServico,
							"id_midia" => $inputMidia, 
							"id_empresa" => $idEmpresa,
							"id_consultor" => $inputConsultor,
							"id_forma_pagamento" => $inputFormaPagamento,
							"valor_proposta" => $inputValordePagamento,
							"marca_veiculo" => $inputMarcaVeiculo,
							"modelo_veiculo" => $inputModeloVeiculo,
							"ano_veiculo" => $inputAnoVeiculo,
							"ano_modelo_veiculo" => $inputAnoModeloVeiculo,
							"placa_veiculo" => $inputPlacaVeiculo,
							"numero_parcelas_financiamento" => $inputNumeroParcelas,
							"valor_parcela_financiamento" => $inputValorParcelas,
							"instituicao_financeira" => $inputInstituicao,
							"quantidade" => $inputQuantidadeServico,
							"valor_entrada" => $inputValorEntrada,
							"numero_parcelas_servico" => $inputNumeroParcelasServico,
							"dt_agendamento" => $inputDataAgendamento." 00:00",
							"observacao" => $observacao];

			return $httpProvider->requestHttpWithToken("POST", $requestBody, "cliente/atendimento", $_SESSION["token"]);
		}
	

		function incluirClienteBasico($nome, $email, $telefone, $celular, $consultor, $midia, $statusAtendimento, $observacao, $dataAgendamento, $idEmpresa, $idUsuario){
			$httpProvider = new HttpProvider();
			$requestBody = ["id_usuario_inclusao" => $idUsuario,
							"id_usuario_alteracao" => $idUsuario,
							"nome_cliente" => $nome,
							"email" => $email,
							"telefone" => $telefone,
							"celular" => $celular,
							"rg" => "",
							"cpf" => "",
							"endereco" => "",
							"numero" => "",
							"complemento" => "",
							"bairro" => "",
							"cep" => "",
							"estado" => "",
							"cidade" => "",
							"uf" => "",
							"endereco_comercial" => "",
							"telefone_comercial" => "",
							"estado_civil" => "",
							"profissao" => "",
							"data_nasc" => "",
							"cnh" => "",
							"validade_cnh" => "",
							"categoria_cnh" => "",
							"cidade_estado_cnh" => "",
							"id_status_atendimento" => "",
							"id_fluxo_atendimento" => $statusAtendimento,
							"id_servico" => "",
							"id_midia" => $midia, 
							"id_empresa" => $idEmpresa,
							"id_consultor" => $consultor,
							"id_forma_pagamento" => "",
							"valor_proposta" => "",
							"marca_veiculo" => "",
							"modelo_veiculo" => "",
							"ano_veiculo" => "",
							"ano_modelo_veiculo" => "",
							"placa_veiculo" => "",
							"numero_parcelas_financiamento" => "",
							"valor_parcela_financiamento" => "",
							"instituicao_financeira" => "",
							"quantidade" => "",
							"valor_entrada" => "",
							"numero_parcelas_servico" => "",
							"dt_agendamento" => $dataAgendamento,
							"observacao" => $observacao];

			return $httpProvider->requestHttpWithToken("POST", $requestBody, "cliente/inicial", $_SESSION["token"]);
		}

		function atualizarAtendimentoBasico($nome, $email, $telefone, $celular, $consultor, $midia, $statusAtendimento, $observacao, $dataAgendamento, $idEmpresa, $idUsuario){
			$httpProvider = new HttpProvider();
			$requestBody = ["id_usuario_inclusao" => $idUsuario,
							"id_usuario_alteracao" => $idUsuario,
							"nome_cliente" => $nome,
							"email" => $email,
							"telefone" => $telefone,
							"celular" => $celular,
							"rg" => "",
							"cpf" => "",
							"endereco" => "",
							"numero" => "",
							"complemento" => "",
							"bairro" => "",
							"cep" => "",
							"estado" => "",
							"cidade" => "",
							"uf" => "",
							"endereco_comercial" => "",
							"telefone_comercial" => "",
							"estado_civil" => "",
							"profissao" => "",
							"data_nasc" => "",
							"cnh" => "",
							"validade_cnh" => "",
							"categoria_cnh" => "",
							"cidade_estado_cnh" => "",
							"id_status_atendimento" => "",
							"id_fluxo_atendimento" => $statusAtendimento,
							"id_servico" => "",
							"id_midia" => $midia, 
							"id_empresa" => $idEmpresa,
							"id_consultor" => $consultor,
							"id_forma_pagamento" => "",
							"valor_proposta" => "",
							"marca_veiculo" => "",
							"modelo_veiculo" => "",
							"ano_veiculo" => "",
							"ano_modelo_veiculo" => "",
							"placa_veiculo" => "",
							"numero_parcelas_financiamento" => "",
							"valor_parcela_financiamento" => "",
							"instituicao_financeira" => "",
							"quantidade" => "",
							"valor_entrada" => "",
							"numero_parcelas_servico" => "",
							"dt_agendamento" => $dataAgendamento,
							"observacao" => $observacao];

			return $httpProvider->requestHttpWithToken("PUT", $requestBody, "cliente/inicial", $_SESSION["token"]);
		}

		

		function atualizarCliente($inputNome, $inputEmail, $inputTelefone, $inputCelular, $inputNascimento,
									$inputRg, $inputCpf, $inputEstadoCivil, $inputProfissao, $inputCep, $inputEndereco,
									$inputEnderecoNumero, $inputEnderecoComplemento, $inputEnderecoBairro, $inputEnderecoCidade,
									$inputEnderecoEstado, $inputEnderecoUf, $inputEnderecoComercial, $inputTelefoneComercial,
									$inputNumeroCnh, $inputValidadeCnh, $inputCategoriaCnh, $inputCidadeEstadoCnh, $inputServico,
										$inputConsultor, $inputMidia, $inputFormaPagamento, $inputFluxoAtendimento, $inputQuantidadeServico,
										$inputNumeroParcelas, $inputValorParcelas, $inputInstituicao, $inputValordePagamento, $inputValorEntrada,
										$inputNumeroParcelasServico, $inputMarcaVeiculo, $inputModeloVeiculo, $inputAnoVeiculo, $inputAnoModeloVeiculo,
										$inputPlacaVeiculo, $idAtendimento, $observacao, $inputDataAgendamento, $idCliente, $idUsuario, $idEmpresa){
			$httpProvider = new HttpProvider();
			$requestBody = ["id_usuario_inclusao" => "",
							"id_usuario_alteracao" => $idUsuario,
							"nome_cliente" => $inputNome,
							"email" => $inputEmail,
							"telefone" => $inputTelefone,
							"celular" => $inputCelular,
							"rg" => $inputRg,
							"cpf" => $inputCpf,
							"endereco" => $inputEndereco,
							"numero" => $inputEnderecoNumero,
							"complemento" => $inputEnderecoComplemento,
							"bairro" => $inputEnderecoBairro,
							"cep" => $inputCep,
							"estado" => $inputEnderecoEstado,
							"cidade" => $inputEnderecoCidade,
							"uf" => $inputEnderecoUf,
							"endereco_comercial" => $inputEnderecoComercial,
							"telefone_comercial" => $inputTelefoneComercial,
							"estado_civil" => $inputEstadoCivil,
							"profissao" => $inputProfissao,
							"data_nasc" => $inputNascimento,
							"cnh" => $inputNumeroCnh,
							"validade_cnh" => $inputValidadeCnh,
							"categoria_cnh" => $inputCategoriaCnh,
							"cidade_estado_cnh" => $inputCidadeEstadoCnh,
							"id_fluxo_atendimento" => $inputFluxoAtendimento,
							"id_servico" => $inputServico,
							"id_midia" => $inputMidia, 
							"id_empresa" => $idEmpresa,
							"id_consultor" => $inputConsultor,
							"id_forma_pagamento" => $inputFormaPagamento,
							"valor_proposta" => $inputValordePagamento,
							"marca_veiculo" => $inputMarcaVeiculo,
							"modelo_veiculo" => $inputModeloVeiculo,
							"ano_veiculo" => $inputAnoVeiculo,
							"ano_modelo_veiculo" => $inputAnoModeloVeiculo,
							"placa_veiculo" => $inputPlacaVeiculo,
							"numero_parcelas_financiamento" => $inputNumeroParcelas,
							"valor_parcela_financiamento" => $inputValorParcelas,
							"instituicao_financeira" => $inputInstituicao,
							"quantidade" => $inputQuantidadeServico,
							"valor_entrada" => $inputValorEntrada,
							"numero_parcelas_servico" => $inputNumeroParcelasServico,
							"dt_agendamento" => $inputDataAgendamento." 00:00",
							"observacao" => $observacao];

			return $httpProvider->requestHttpWithToken("PUT", $requestBody, "cliente/".$idCliente."/atendimento/".$idAtendimento, $_SESSION["token"]);
		}
	}		
	
?>